version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[deploy skip]"
    rebase-strategy: "disabled"
